GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
POST http://localhost:8080/users/
Content-Type: application/json

{
    "name": "woe Doe",
    "email": "joniisn@gmail.com",
    "gender": "male"
}

###
PATCH  http://localhost:8080/users/1
Content-Type: application/json

{
    "name": "kontol",
    "email": "jonisins@gmail.com",
    "gender": "male"
}

###
DELETE http://localhost:8080/users/1